# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.13'
  
variables:
  scheme: 'GooglePromiseDemo'
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
- script: /usr/local/bin/carthage update --platform ios
  displayName: 'Carthage Update'
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcWorkspacePath: '**/$(scheme).xcodeproj/project.xcworkspace'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: /Applications/Xcode_10.1.app
